theme: minima
title: Metabloggism
author: Ignasi Mas
description: AI engineer and tech adventurer. I love learning so I learned Machine Learning for learning how to make Machines learn, but in my way I learned that I had learned for learning how to make Machines Learn to Learn. You may note my interest in Meta-Learning.
